name = "tmpimg"
account_id = ""
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
main = "./dist/index.mjs"

assets = { directory = "./public/", binding = "ASSETS" }

[build]
command = "npm install && npm run build"

[[rules]]
type = "Data"
globs = [ "**/*.ttf", "**/*.otf" ]
fallthrough = true
