name = "tmpimg"
account_id = ""
workers_dev = true
compatibility_date = "2024-09-23"
main = "./dist/index.mjs"

[build]
command = "npm install && npm run build"

[[rules]]
type = "Data"
globs = [ "**/*.ttf", "**/*.otf" ]
fallthrough = true
